// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// binariseCpp
NumericVector binariseCpp(NumericVector& vals, double thresh);
RcppExport SEXP _mosaik_binariseCpp(SEXP valsSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(binariseCpp(vals, thresh));
    return rcpp_result_gen;
END_RCPP
}
// cellToPointsCpp
DataFrame cellToPointsCpp(NumericMatrix mat);
RcppExport SEXP _mosaik_cellToPointsCpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cellToPointsCpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// componentsCpp
IntegerVector componentsCpp(NumericVector& vals, int nrow, int ncol, int connectivity);
RcppExport SEXP _mosaik_componentsCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP connectivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type connectivity(connectivitySEXP);
    rcpp_result_gen = Rcpp::wrap(componentsCpp(vals, nrow, ncol, connectivity));
    return rcpp_result_gen;
END_RCPP
}
// costDistanceCpp
List costDistanceCpp(NumericVector cost, IntegerVector from, int nrow, int ncol, bool diagonal);
RcppExport SEXP _mosaik_costDistanceCpp(SEXP costSEXP, SEXP fromSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP diagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cost(costSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(costDistanceCpp(cost, from, nrow, ncol, diagonal));
    return rcpp_result_gen;
END_RCPP
}
// countCellAdjacenciesCpp
NumericMatrix countCellAdjacenciesCpp(NumericVector& vals, int nrow, int ncol, bool doublecount, bool eightconn);
RcppExport SEXP _mosaik_countCellAdjacenciesCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP doublecountSEXP, SEXP eightconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< bool >::type doublecount(doublecountSEXP);
    Rcpp::traits::input_parameter< bool >::type eightconn(eightconnSEXP);
    rcpp_result_gen = Rcpp::wrap(countCellAdjacenciesCpp(vals, nrow, ncol, doublecount, eightconn));
    return rcpp_result_gen;
END_RCPP
}
// countCellEdgesCpp
DataFrame countCellEdgesCpp(NumericVector& vals, int nrow, int ncol);
RcppExport SEXP _mosaik_countCellEdgesCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(countCellEdgesCpp(vals, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// countCellValuesCpp
DataFrame countCellValuesCpp(NumericVector& vals, int nrow, int ncol);
RcppExport SEXP _mosaik_countCellValuesCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(countCellValuesCpp(vals, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// diamondSquareCpp
NumericMatrix diamondSquareCpp(NumericMatrix mat, NumericVector stepSize, double roughness, double startDev);
RcppExport SEXP _mosaik_diamondSquareCpp(SEXP matSEXP, SEXP stepSizeSEXP, SEXP roughnessSEXP, SEXP startDevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stepSize(stepSizeSEXP);
    Rcpp::traits::input_parameter< double >::type roughness(roughnessSEXP);
    Rcpp::traits::input_parameter< double >::type startDev(startDevSEXP);
    rcpp_result_gen = Rcpp::wrap(diamondSquareCpp(mat, stepSize, roughness, startDev));
    return rcpp_result_gen;
END_RCPP
}
// distanceFromPointsCpp
NumericVector distanceFromPointsCpp(double xmin, double ymax, double res_x, double res_y, int ncol, int nrow, NumericMatrix coords);
RcppExport SEXP _mosaik_distanceFromPointsCpp(SEXP xminSEXP, SEXP ymaxSEXP, SEXP res_xSEXP, SEXP res_ySEXP, SEXP ncolSEXP, SEXP nrowSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< double >::type res_y(res_ySEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(distanceFromPointsCpp(xmin, ymax, res_x, res_y, ncol, nrow, coords));
    return rcpp_result_gen;
END_RCPP
}
// getValuesCpp
NumericVector getValuesCpp(NumericMatrix& mat);
RcppExport SEXP _mosaik_getValuesCpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(getValuesCpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// isBinaryCpp
bool isBinaryCpp(NumericVector& vals);
RcppExport SEXP _mosaik_isBinaryCpp(SEXP valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    rcpp_result_gen = Rcpp::wrap(isBinaryCpp(vals));
    return rcpp_result_gen;
END_RCPP
}
// distanceCpp
NumericVector distanceCpp(NumericVector& vals, int nrow, int ncol, String method);
RcppExport SEXP _mosaik_distanceCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(distanceCpp(vals, nrow, ncol, method));
    return rcpp_result_gen;
END_RCPP
}
// matInGeomCpp
NumericMatrix matInGeomCpp(NumericMatrix& mat, NumericMatrix& geom, bool negative);
RcppExport SEXP _mosaik_matInGeomCpp(SEXP matSEXP, SEXP geomSEXP, SEXP negativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type geom(geomSEXP);
    Rcpp::traits::input_parameter< bool >::type negative(negativeSEXP);
    rcpp_result_gen = Rcpp::wrap(matInGeomCpp(mat, geom, negative));
    return rcpp_result_gen;
END_RCPP
}
// reduceCpp
NumericVector reduceCpp(List lVals, Function f);
RcppExport SEXP _mosaik_reduceCpp(SEXP lValsSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lVals(lValsSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(reduceCpp(lVals, f));
    return rcpp_result_gen;
END_RCPP
}
// scaleMatrixCpp
NumericMatrix scaleMatrixCpp(NumericMatrix mat, NumericVector range);
RcppExport SEXP _mosaik_scaleMatrixCpp(SEXP matSEXP, SEXP rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range(rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleMatrixCpp(mat, range));
    return rcpp_result_gen;
END_RCPP
}
// morphCpp
NumericVector morphCpp(NumericVector& vals, int valRows, int valCols, NumericMatrix& kernel, NumericVector& value, int blend, int merge, bool rotateKernel, bool strictKernel);
RcppExport SEXP _mosaik_morphCpp(SEXP valsSEXP, SEXP valRowsSEXP, SEXP valColsSEXP, SEXP kernelSEXP, SEXP valueSEXP, SEXP blendSEXP, SEXP mergeSEXP, SEXP rotateKernelSEXP, SEXP strictKernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type valRows(valRowsSEXP);
    Rcpp::traits::input_parameter< int >::type valCols(valColsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type blend(blendSEXP);
    Rcpp::traits::input_parameter< int >::type merge(mergeSEXP);
    Rcpp::traits::input_parameter< bool >::type rotateKernel(rotateKernelSEXP);
    Rcpp::traits::input_parameter< bool >::type strictKernel(strictKernelSEXP);
    rcpp_result_gen = Rcpp::wrap(morphCpp(vals, valRows, valCols, kernel, value, blend, merge, rotateKernel, strictKernel));
    return rcpp_result_gen;
END_RCPP
}
// patchAdjacencyCpp
List patchAdjacencyCpp(IntegerVector& labels, int nrow, int ncol, bool eightconn);
RcppExport SEXP _mosaik_patchAdjacencyCpp(SEXP labelsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP eightconnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< bool >::type eightconn(eightconnSEXP);
    rcpp_result_gen = Rcpp::wrap(patchAdjacencyCpp(labels, nrow, ncol, eightconn));
    return rcpp_result_gen;
END_RCPP
}
// percolationCpp
IntegerVector percolationCpp(int ncol, int nrow, double p);
RcppExport SEXP _mosaik_percolationCpp(SEXP ncolSEXP, SEXP nrowSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(percolationCpp(ncol, nrow, p));
    return rcpp_result_gen;
END_RCPP
}
// perlinCpp
NumericVector perlinCpp(int ncol, int nrow, double freq, double offset_x, double offset_y);
RcppExport SEXP _mosaik_perlinCpp(SEXP ncolSEXP, SEXP nrowSEXP, SEXP freqSEXP, SEXP offset_xSEXP, SEXP offset_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< double >::type offset_x(offset_xSEXP);
    Rcpp::traits::input_parameter< double >::type offset_y(offset_ySEXP);
    rcpp_result_gen = Rcpp::wrap(perlinCpp(ncol, nrow, freq, offset_x, offset_y));
    return rcpp_result_gen;
END_RCPP
}
// pointInPolyCpp
IntegerVector pointInPolyCpp(NumericMatrix& vert, NumericMatrix& geom, bool invert);
RcppExport SEXP _mosaik_pointInPolyCpp(SEXP vertSEXP, SEXP geomSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type vert(vertSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type geom(geomSEXP);
    Rcpp::traits::input_parameter< bool >::type invert(invertSEXP);
    rcpp_result_gen = Rcpp::wrap(pointInPolyCpp(vert, geom, invert));
    return rcpp_result_gen;
END_RCPP
}
// rescaleGridCpp
List rescaleGridCpp(NumericVector& vals, int nrow, int ncol, double factorRow, double factorCol);
RcppExport SEXP _mosaik_rescaleGridCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP factorRowSEXP, SEXP factorColSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type factorRow(factorRowSEXP);
    Rcpp::traits::input_parameter< double >::type factorCol(factorColSEXP);
    rcpp_result_gen = Rcpp::wrap(rescaleGridCpp(vals, nrow, ncol, factorRow, factorCol));
    return rcpp_result_gen;
END_RCPP
}
// simplexCpp
NumericVector simplexCpp(int ncol, int nrow, double freq, double offset_x, double offset_y);
RcppExport SEXP _mosaik_simplexCpp(SEXP ncolSEXP, SEXP nrowSEXP, SEXP freqSEXP, SEXP offset_xSEXP, SEXP offset_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< double >::type offset_x(offset_xSEXP);
    Rcpp::traits::input_parameter< double >::type offset_y(offset_ySEXP);
    rcpp_result_gen = Rcpp::wrap(simplexCpp(ncol, nrow, freq, offset_x, offset_y));
    return rcpp_result_gen;
END_RCPP
}
// skeletoniseCpp
IntegerVector skeletoniseCpp(NumericVector& vals, int nrow, int ncol, NumericVector anchor, bool homotopic);
RcppExport SEXP _mosaik_skeletoniseCpp(SEXP valsSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP anchorSEXP, SEXP homotopicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type homotopic(homotopicSEXP);
    rcpp_result_gen = Rcpp::wrap(skeletoniseCpp(vals, nrow, ncol, anchor, homotopic));
    return rcpp_result_gen;
END_RCPP
}
// slopeAspectCpp
List slopeAspectCpp(NumericVector elev, int nrow, int ncol, double xres, double yres);
RcppExport SEXP _mosaik_slopeAspectCpp(SEXP elevSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP xresSEXP, SEXP yresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type elev(elevSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    rcpp_result_gen = Rcpp::wrap(slopeAspectCpp(elev, nrow, ncol, xres, yres));
    return rcpp_result_gen;
END_RCPP
}
// sortUniqueCpp
NumericVector sortUniqueCpp(NumericVector x);
RcppExport SEXP _mosaik_sortUniqueCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sortUniqueCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// tesselateCpp
IntegerVector tesselateCpp(double xmin, double ymax, double res_x, double res_y, int ncol, int nrow, NumericVector seed_x, NumericVector seed_y, IntegerVector seed_val);
RcppExport SEXP _mosaik_tesselateCpp(SEXP xminSEXP, SEXP ymaxSEXP, SEXP res_xSEXP, SEXP res_ySEXP, SEXP ncolSEXP, SEXP nrowSEXP, SEXP seed_xSEXP, SEXP seed_ySEXP, SEXP seed_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< double >::type res_y(res_ySEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seed_x(seed_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seed_y(seed_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seed_val(seed_valSEXP);
    rcpp_result_gen = Rcpp::wrap(tesselateCpp(xmin, ymax, res_x, res_y, ncol, nrow, seed_x, seed_y, seed_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mosaik_binariseCpp", (DL_FUNC) &_mosaik_binariseCpp, 2},
    {"_mosaik_cellToPointsCpp", (DL_FUNC) &_mosaik_cellToPointsCpp, 1},
    {"_mosaik_componentsCpp", (DL_FUNC) &_mosaik_componentsCpp, 4},
    {"_mosaik_costDistanceCpp", (DL_FUNC) &_mosaik_costDistanceCpp, 5},
    {"_mosaik_countCellAdjacenciesCpp", (DL_FUNC) &_mosaik_countCellAdjacenciesCpp, 5},
    {"_mosaik_countCellEdgesCpp", (DL_FUNC) &_mosaik_countCellEdgesCpp, 3},
    {"_mosaik_countCellValuesCpp", (DL_FUNC) &_mosaik_countCellValuesCpp, 3},
    {"_mosaik_diamondSquareCpp", (DL_FUNC) &_mosaik_diamondSquareCpp, 4},
    {"_mosaik_distanceFromPointsCpp", (DL_FUNC) &_mosaik_distanceFromPointsCpp, 7},
    {"_mosaik_getValuesCpp", (DL_FUNC) &_mosaik_getValuesCpp, 1},
    {"_mosaik_isBinaryCpp", (DL_FUNC) &_mosaik_isBinaryCpp, 1},
    {"_mosaik_distanceCpp", (DL_FUNC) &_mosaik_distanceCpp, 4},
    {"_mosaik_matInGeomCpp", (DL_FUNC) &_mosaik_matInGeomCpp, 3},
    {"_mosaik_reduceCpp", (DL_FUNC) &_mosaik_reduceCpp, 2},
    {"_mosaik_scaleMatrixCpp", (DL_FUNC) &_mosaik_scaleMatrixCpp, 2},
    {"_mosaik_morphCpp", (DL_FUNC) &_mosaik_morphCpp, 9},
    {"_mosaik_patchAdjacencyCpp", (DL_FUNC) &_mosaik_patchAdjacencyCpp, 4},
    {"_mosaik_percolationCpp", (DL_FUNC) &_mosaik_percolationCpp, 3},
    {"_mosaik_perlinCpp", (DL_FUNC) &_mosaik_perlinCpp, 5},
    {"_mosaik_pointInPolyCpp", (DL_FUNC) &_mosaik_pointInPolyCpp, 3},
    {"_mosaik_rescaleGridCpp", (DL_FUNC) &_mosaik_rescaleGridCpp, 5},
    {"_mosaik_simplexCpp", (DL_FUNC) &_mosaik_simplexCpp, 5},
    {"_mosaik_skeletoniseCpp", (DL_FUNC) &_mosaik_skeletoniseCpp, 5},
    {"_mosaik_slopeAspectCpp", (DL_FUNC) &_mosaik_slopeAspectCpp, 5},
    {"_mosaik_sortUniqueCpp", (DL_FUNC) &_mosaik_sortUniqueCpp, 1},
    {"_mosaik_tesselateCpp", (DL_FUNC) &_mosaik_tesselateCpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mosaik(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
