# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binarise cell values by a threshold (c++)
#'
#' C++ function that converts a numeric vector to binary (0/1) values based on
#' a threshold. Values >= thresh become 1, values < thresh become 0, NA stays
#' NA.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values.
#' @param thresh [numeric(1)][numeric]\cr threshold value.
#' @return A numeric vector of the same length with binary values.
#' @noRd
binariseCpp <- function(vals, thresh) {
    .Call(`_mosaik_binariseCpp`, vals, thresh)
}

#' Cell coordinates to data.frame (c++)
#'
#' C++ function that converts the cell coordinates of a matrix to a data.frame.
#' @param mat [matrix(numeric)][matrix]\cr object of which the cell coordinates
#'   are converted to a data.frame.
#' @return a data.frame of the cell coordinates
#' @noRd
cellToPointsCpp <- function(mat) {
    .Call(`_mosaik_cellToPointsCpp`, mat)
}

#' Connected-component labeling (c++)
#'
#' C++ function that labels connected components in a gridded object using a
#' two-pass union-find algorithm.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values (row-major
#'   order).
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param connectivity [integer(1)][integer]\cr neighbourhood connectivity;
#'   \code{4} for rook/diamond (up/down/left/right) or \code{8} for
#'   queen/box (including diagonals). Default is \code{4}.
#' @return An integer vector of the same length where each connected component
#'   of non-NA cells sharing the same value has a unique label. NA cells remain
#'   NA.
#' @noRd
componentsCpp <- function(vals, nrow, ncol, connectivity = 4L) {
    .Call(`_mosaik_componentsCpp`, vals, nrow, ncol, connectivity)
}

#' Cost-distance and shortest path on a grid (C++)
#'
#' Dijkstra's algorithm on a regular grid with per-cell traversal costs.
#' Returns both the cumulative cost surface and a predecessor map for
#' path tracing.
#'
#' @param cost [numeric(.)][numeric]\cr flat vector of per-cell traversal
#'   costs (row-major order).  Values must be >= 0.  NA cells are
#'   impassable barriers.
#' @param from [integer(.)][integer]\cr 1-based cell indices of source
#'   cells.
#' @param nrow [integer(1)][integer]\cr number of rows in the grid.
#' @param ncol [integer(1)][integer]\cr number of columns in the grid.
#' @param diagonal [logical(1)][logical]\cr if TRUE, use 8-connectivity
#'   (diagonal moves cost sqrt(2) * average cost).  If FALSE, use
#'   4-connectivity (rook moves only).
#' @return A list with two elements:
#'   \describe{
#'     \item{dist}{Numeric vector of cumulative cost-distances from the
#'       nearest source.  Inf for unreachable cells.}
#'     \item{pred}{Integer vector of 1-based predecessor cell indices
#'       (-1 for source cells, 0 for unreachable cells).  Walk
#'       backwards from any target cell to reconstruct the path.}
#'   }
#' @family grid utility functions
#' @noRd
costDistanceCpp <- function(cost, from, nrow, ncol, diagonal) {
    .Call(`_mosaik_costDistanceCpp`, cost, from, nrow, ncol, diagonal)
}

#' Count cell adjacencies in a grid (c++)
#'
#' C++ function that counts the adjacencies between unique values in a flat
#' grid vector
#' @param vals [numeric][numeric]\cr the values to analyse (row-major flat
#'   vector)
#' @param nrow [integer(1)][integer]\cr number of rows in the grid
#' @param ncol [integer(1)][integer]\cr number of columns in the grid
#' @param doublecount [logical(1)][logical]\cr whether or not to tally up each
#'   adjacency for both neighbouring cells, or only once.
#' @param eightconn [logical(1)][logical]\cr whether to use 8-connectivity
#'   (queen: also count the four diagonal neighbours) or 4-connectivity (rook:
#'   orthogonal neighbours only).
#' @family count functions
#' @return A matrix of values*values with their adjacencies
#' @noRd
countCellAdjacenciesCpp <- function(vals, nrow, ncol, doublecount, eightconn = FALSE) {
    .Call(`_mosaik_countCellAdjacenciesCpp`, vals, nrow, ncol, doublecount, eightconn)
}

#' Count cell edges in a grid (c++)
#'
#' C++ function that counts the number of edges between different values in a
#' flat grid vector
#' @param vals [numeric][numeric]\cr the values to analyse (row-major flat
#'   vector)
#' @param nrow [integer(1)][integer]\cr number of rows in the grid
#' @param ncol [integer(1)][integer]\cr number of columns in the grid
#' @family count functions
#' @return A data.frame of the unique values and their edges in X and Y
#' @noRd
countCellEdgesCpp <- function(vals, nrow, ncol) {
    .Call(`_mosaik_countCellEdgesCpp`, vals, nrow, ncol)
}

#' Count unique cell values in a grid (c++)
#'
#' C++ function that counts the number of unique values in a flat grid vector
#' @param vals [numeric][numeric]\cr the values to count (column-major flat
#'   vector)
#' @param nrow [integer(1)][integer]\cr number of rows in the grid
#' @param ncol [integer(1)][integer]\cr number of columns in the grid
#' @family count functions
#' @return A data.frame of the unique values and their number
#' @noRd
countCellValuesCpp <- function(vals, nrow, ncol) {
    .Call(`_mosaik_countCellValuesCpp`, vals, nrow, ncol)
}

#' Generate a height map (c++)
#'
#' C++ function that generates a height map based on the diamond-square
#' algorithm
#' @param mat [matrix(numeric)][matrix]\cr the template matrix into which
#'   height values are written.
#' @param stepSize [numeric(.)][numeric]\cr the side length of the squares at
#'   each iteration, largest first, each half the one before; the first is the
#'   side of \code{mat} minus one.
#' @param roughness [numeric(1)][numeric]\cr the Hurst exponent (fBm) or its
#'   equivalent, the roughness factor (DSa). Bounded between 0 and 1.
#' @param startDev [numeric(1)][numeric]\cr standard deviation of the random
#'   offset at the first iteration; it shrinks by \code{0.5^roughness} at each
#'   following one.
#' @family matrix modify functions
#' @return A numeric matrix of the same dimensions as \code{mat} into which the
#'   values of a height map have been written.
#' @noRd
diamondSquareCpp <- function(mat, stepSize, roughness, startDev) {
    .Call(`_mosaik_diamondSquareCpp`, mat, stepSize, roughness, startDev)
}

#' Get Matrix cell values (c++)
#'
#' C++ function that extracts the values of a matrix
#' @param mat [matrix(numeric)][matrix]\cr the matrix from which to extract the values.
#' @family extractor functions
#' @return numeric vector of the values in \code{mat}
#' @noRd
getValuesCpp <- function(mat) {
    .Call(`_mosaik_getValuesCpp`, mat)
}

#' Check whether cell values are binary (c++)
#'
#' C++ function that checks if all non-NA values in a numeric vector are
#' either 0 or 1.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values.
#' @return A single logical value.
#' @noRd
isBinaryCpp <- function(vals) {
    .Call(`_mosaik_isBinaryCpp`, vals)
}

#' Calculate a distance map (c++)
#'
#' C++ function that derives a distance map of foreground patches in a flat
#' grid vector.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values
#'   (row-major order). Foreground cells have value 1.
#' @param nrow [integer(1)][integer]\cr number of rows in the grid.
#' @param ncol [integer(1)][integer]\cr number of columns in the grid.
#' @param method [character(1)][character]\cr which of the methods
#'   \code{"euclidean"}, \code{"manhattan"} or \code{"chessboard"} to use.
#' @family grid modify functions
#' @return A numeric vector of the same length with distance values.
#' @noRd
distanceCpp <- function(vals, nrow, ncol, method) {
    .Call(`_mosaik_distanceCpp`, vals, nrow, ncol, method)
}

#' Cell (matrix) in polygon algorithm (c++)
#'
#' C++ function that determine whether the cells in a matrix are inside or
#' outside of a polygon.
#' @param mat [matrix(numeric)][matrix]\cr object of which the cell coordinates
#'   are tested against \code{geom}.
#' @param geom [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the polygon, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param negative [logical(1)][logical]\cr whether or not to test points are
#'   outside of a polygon.
#' @details Copyright 2000 softSurfer, 2012 Dan Sunday This code may be freely
#'   used and modified for any purpose providing that this copyright notice is
#'   included with it. SoftSurfer makes no warranty for this code, and cannot
#'   be held liable for any real or imagined damage resulting from its use.
#'   Users of this code must verify correctness for their application.
#' @family topological relationships
#' @return a numeric matrix
#' @noRd
matInGeomCpp <- function(mat, geom, negative) {
    .Call(`_mosaik_matInGeomCpp`, mat, geom, negative)
}

#' Reduce a list of value vectors (c++)
#'
#' C++ function that uses a binary function to successively combine a list
#' of flat value vectors (all of equal length).
#' @param lVals [list(numeric)][list]\cr list of numeric vectors with equal
#'   length.
#' @param f [function(1)][function]\cr binary function to combine the vectors.
#' @return a single numeric vector of the same length as the input vectors.
#' @noRd
reduceCpp <- function(lVals, f) {
    .Call(`_mosaik_reduceCpp`, lVals, f)
}

#' Scale values in a matrix (c++)
#'
#' C++ function that scales the values in a matrix between a provided range
#' @param mat [matrix(numeric)][matrix]\cr object in which the values are
#'   scaled.
#' @param range [numeric(2)][numeric]\cr two values (minimum and maximum)
#'   between which the values in \code{mat} shall be scaled.
#' @family matrix modify functions
#' @return a numeric matrix
#' @noRd
scaleMatrixCpp <- function(mat, range) {
    .Call(`_mosaik_scaleMatrixCpp`, mat, range)
}

#' Morphological operation on a gridded object (c++)
#'
#' C++ function that applies a morphological operation to a gridded object.
#' The function slides a kernel over the grid, blends the neighborhood values
#' with the kernel, and merges the result into a single output value per cell.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values
#'   (row-major order).
#' @param valRows [integer(1)][integer]\cr number of rows in the grid.
#' @param valCols [integer(1)][integer]\cr number of columns in the grid.
#' @param kernel [matrix(numeric)][matrix]\cr the structuring element. NA
#'   cells in the kernel are ignored.
#' @param value [numeric(.)][numeric]\cr which cell values to process. Cells
#'   whose value is not in this vector are left unchanged.
#' @param blend [integer(1)][integer]\cr blend mode (1-indexed): 1=identity,
#'   2=equal, 3=lower, 4=greater, 5=plus, 6=minus, 7=product.
#' @param merge [integer(1)][integer]\cr merge mode (1-indexed): 1=min,
#'   2=max, 3=all, 4=any, 5=!all, 6=!any, 7=sum, 8=mean, 9=median, 10=sd,
#'   11=cv, 12=sumNa.
#' @param rotateKernel [logical(1)][logical]\cr whether to try all 4 rotations
#'   of the kernel (useful for hit-or-miss transforms). Needs a square kernel.
#' @param strictKernel [logical(1)][logical]\cr whether the kernel must fit
#'   entirely within the grid (TRUE) or is clipped at borders (FALSE).
#' @return A numeric vector of the same length as \code{vals} with the
#'   morphological operation applied.
#' @noRd
morphCpp <- function(vals, valRows, valCols, kernel, value, blend, merge, rotateKernel, strictKernel) {
    .Call(`_mosaik_morphCpp`, vals, valRows, valCols, kernel, value, blend, merge, rotateKernel, strictKernel)
}

#' Patch-adjacency and contact regions on a labelled grid (c++)
#'
#' Given a grid of patch labels (e.g. from \code{componentsCpp}), count for
#' every ordered pair of distinct patches (i) how many adjacent cell pairs
#' connect them (contact length) and (ii) in how many spatially distinct
#' places they touch (contact regions). The second is the loop-vs-branch
#' discriminator for MSPA and is not derivable from the first.
#'
#' @param labels [integer(.)][integer]\cr flat vector of patch labels
#'   (row-major). NA cells are ignored.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param eightconn [logical(1)][logical]\cr 8-connectivity (queen) if TRUE,
#'   4-connectivity (rook) if FALSE, for what counts as contact between two
#'   patches.
#' @return A list with \code{ids} (sorted unique patch labels, the row/column
#'   order of both matrices), \code{adjacency} (double-counted cell-pair
#'   contacts), and \code{regions} (distinct contact regions per pair).
#' @details Contact-cell linkage for the region count is always 8-connected:
#'   two contact cells belonging to the same patch pair are the same region if
#'   they are queen-adjacent. This is independent of \code{eightconn}, which
#'   only governs whether two patches are considered in contact at all.
#' @noRd
patchAdjacencyCpp <- function(labels, nrow, ncol, eightconn) {
    .Call(`_mosaik_patchAdjacencyCpp`, labels, nrow, ncol, eightconn)
}

#' Binary percolation grid (c++)
#'
#' Generate a binary grid where each cell is independently set to 1 with
#' probability \code{p} and 0 otherwise.
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param p [numeric(1)][numeric]\cr probability of a cell being 1.
#' @return An integer vector of length \code{ncol * nrow} with values 0 or 1.
#' @noRd
percolationCpp <- function(ncol, nrow, p) {
    .Call(`_mosaik_percolationCpp`, ncol, nrow, p)
}

#' 2D Perlin noise (c++)
#'
#' Evaluate improved Perlin noise at each cell centroid. Output is in
#' approximately \[-1, 1\].
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param freq [numeric(1)][numeric]\cr spatial frequency — how many noise
#'   periods fit across the grid.
#' @param offset_x [numeric(1)][numeric]\cr x offset for tiling/seeding.
#' @param offset_y [numeric(1)][numeric]\cr y offset for tiling/seeding.
#' @return A numeric vector of length \code{ncol * nrow}.
#' @noRd
perlinCpp <- function(ncol, nrow, freq, offset_x, offset_y) {
    .Call(`_mosaik_perlinCpp`, ncol, nrow, freq, offset_x, offset_y)
}

#' Point in polygon algorithm (c++)
#'
#' C++ function that determine whether points are inside, outside or on the
#' boundary of a polygon.
#' @param vert [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the points, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param geom [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the polygon, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param invert [logical(1)][logical]\cr whether or not to test instead for
#'   points that are outside of the polygon.
#' @details This is an extension of the below described algorithm. It extends
#'   the "point in polygon" algorithm, which gives values 0 and 1 for points
#'   that are outside or inside of a polygon, respectively, by the values 2 and
#'   3, for points that are on one or two lines (a vertex) of the polygon,
#'   respectively (which is obviously a stark simplification that depends on
#'   the precision of floating-point values, but can be useful in some edge
#'   cases).
#'
#'   http://www.geomalgorithms.com/ Copyright 2000 softSurfer, 2012 Dan Sunday
#'   This code may be freely used and modified for any purpose providing that
#'   this copyright notice is included with it. SoftSurfer makes no warranty
#'   for this code, and cannot be held liable for any real or imagined damage
#'   resulting from its use. Users of this code must verify correctness for
#'   their application.
#' @family topological relationships
#' @return an integer vector of the same length as there are points in
#'   \code{vert} that indicates where the respective point is located.
#' @noRd
pointInPolyCpp <- function(vert, geom, invert) {
    .Call(`_mosaik_pointInPolyCpp`, vert, geom, invert)
}

#' Rescale a gridded object by a factor (c++)
#'
#' C++ function that rescales a grid using nearest-neighbor resampling.
#' Operates on a flat vector (row-major) without requiring an R matrix.
#' @param vals [numeric(.)][numeric]\cr flat vector of cell values
#'   (row-major order).
#' @param nrow [integer(1)][integer]\cr number of rows in the input.
#' @param ncol [integer(1)][integer]\cr number of columns in the input.
#' @param factorRow [numeric(1)][numeric]\cr scaling factor for rows.
#' @param factorCol [numeric(1)][numeric]\cr scaling factor for columns.
#' @return A numeric vector of the rescaled grid in row-major order.
#'   The output dimensions are floor(nrow * factorRow) x floor(ncol *
#'   factorCol).
#' @details Uses nearest-neighbor interpolation. Each output cell maps back
#'   to the closest input cell. This is equivalent to
#'   \code{mmand::rescale()} with a box kernel for integer scaling factors.
#' @noRd
rescaleGridCpp <- function(vals, nrow, ncol, factorRow, factorCol) {
    .Call(`_mosaik_rescaleGridCpp`, vals, nrow, ncol, factorRow, factorCol)
}

#' 2D Simplex noise (c++)
#'
#' Evaluate simplex noise at each cell centroid. Output is in
#' approximately \[-1, 1\].
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param freq [numeric(1)][numeric]\cr spatial frequency.
#' @param offset_x [numeric(1)][numeric]\cr x offset for seeding.
#' @param offset_y [numeric(1)][numeric]\cr y offset for seeding.
#' @return A numeric vector of length \code{ncol * nrow}.
#' @noRd
simplexCpp <- function(ncol, nrow, freq, offset_x, offset_y) {
    .Call(`_mosaik_simplexCpp`, ncol, nrow, freq, offset_x, offset_y)
}

#' Morphological skeletonisation (c++)
#'
#' C++ function that computes the morphological skeleton of a binary gridded
#' object using the hit-or-miss thinning algorithm. Iteratively removes
#' boundary pixels while preserving topology (connectivity).
#' @param vals [numeric(.)][numeric]\cr flat vector of binary cell values
#'   (row-major order). Must contain only 0, 1, and NA.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param anchor [numeric(.)][numeric]\cr optional flat vector, same length as
#'   \code{vals}, marking anchor cells (non-zero) that are never removed during
#'   thinning. This yields an anchored skeleton whose branches stay connected
#'   to the anchor set and whose free ends rest on it. Pass an all-zero (or
#'   empty) vector for the ordinary unanchored skeleton.
#' @param homotopic [logical(1)][logical]\cr if \code{TRUE}, order-independent
#'   homotopic thinning (Ranwez & Soille 2002) instead of Zhang-Suen.
#' @return An integer vector of the same length with the skeleton (1) and
#'   background (0). NA cells remain NA.
#' @details Zhang-Suen iterates two directional sub-passes. Homotopic thinning
#'   deletes simple points -- cells whose removal keeps both foreground and
#'   background connected as before -- but only those that are also
#'   independent of every simple neighbour, since two adjacent simple pixels
#'   may each be removable alone and not together. That is Ronse's strong
#'   8-deletability, and it is what makes the result independent of the scan
#'   order. Ported from miallib's skel.c (stype 0: foreground 8-connected,
#'   background 4-connected).
#' @noRd
skeletoniseCpp <- function(vals, nrow, ncol, anchor = as.numeric( c()), homotopic = FALSE) {
    .Call(`_mosaik_skeletoniseCpp`, vals, nrow, ncol, anchor, homotopic)
}

slopeAspectCpp <- function(elev, nrow, ncol, xres, yres) {
    .Call(`_mosaik_slopeAspectCpp`, elev, nrow, ncol, xres, yres)
}

#' Extract and sort unique elements (c++)
#'
#' C++ function that extract and returns a sorted vector of numeric values.
#' @param x [numeric(.)][numeric]\cr the vector of numeric values
#' @family extractor functions
#' @return a numeric vector of the unique and sorted values.
#' @noRd
sortUniqueCpp <- function(x) {
    .Call(`_mosaik_sortUniqueCpp`, x)
}

#' Assign each cell to the nearest seed point (c++)
#'
#' For each cell centroid, find the closest seed point (by squared Euclidean
#' distance) and assign the corresponding label.
#' @param xmin [numeric(1)][numeric]\cr left edge of the grid extent.
#' @param ymax [numeric(1)][numeric]\cr top edge of the grid extent.
#' @param res_x [numeric(1)][numeric]\cr cell width.
#' @param res_y [numeric(1)][numeric]\cr cell height.
#' @param ncol [integer(1)][integer]\cr number of columns.
#' @param nrow [integer(1)][integer]\cr number of rows.
#' @param seed_x [numeric][numeric]\cr x coordinates of seed points.
#' @param seed_y [numeric][numeric]\cr y coordinates of seed points.
#' @param seed_val [integer][integer]\cr label for each seed point.
#' @return An integer vector of length \code{ncol * nrow} with the label of the
#'   nearest seed point per cell.
#' @noRd
tesselateCpp <- function(xmin, ymax, res_x, res_y, ncol, nrow, seed_x, seed_y, seed_val) {
    .Call(`_mosaik_tesselateCpp`, xmin, ymax, res_x, res_y, ncol, nrow, seed_x, seed_y, seed_val)
}

